### ISSUE TITLE
Post on persona-check will only send mood

### ISSUE THREAD

**Issue by ChanelZM** [soraya2/vn-seriewijzer#33]
When the user presses the submit button, only checkbox information of the last step will be sent to the server.
Because of disabling step 1 and step 2 only step 3 is sent. Create an overlay when pressing the button on step 3 asking the user for confirmation then send the information to the server.

**Comment by TristanJacobs89** [comment]
Please assign labels.

**Comment by ChanelZM** [comment]
Fixed this bug in an older commit.
